/**
 * DEPRECATED location — kept only as a compatibility shim.
 *
 * The canonical PM2 ecosystem config lives at:
 *   infrastructure/pm2/ecosystem.config.js
 * and is what `yarn pm2:start` uses.
 *
 * This previously divergent root file is now a thin re-export so that
 * `pm2 start ecosystem.config.js` from the repo root still launches the
 * correct, complete five-process set. Do not edit this file — edit the
 * canonical one instead.
 */

module.exports = require("./infrastructure/pm2/ecosystem.config.js");
